// skip 19 cause of backspace
const keyindex = new Map([
    ['q', 0], ['w', 1], ['e', 2], ['r', 3], ['t', 4], ['y', 5], ['u', 6], ['i', 7], ['o', 8], ['p', 9],
    ['a', 10], ['s', 11], ['d', 12], ['f', 13], ['g', 14], ['h', 15], ['j', 16], ['k', 17], ['l', 18],
    ['z', 20], ['x', 21], ['c', 22], ['v', 23], ['b', 24], ['n', 25], ['m', 26]
]);

const allowedKeys = [
    "A", 'a',
    "B", 'b',
    "C", 'c',
    "D", 'd',
    "E", 'e',
    "F", 'f',
    "G", 'g',
    "H", 'h',
    "I", 'i',
    "J", 'j',
    "K", 'k',
    "L", 'l',
    "M", 'm',
    "N", 'n',
    "O", 'o',
    "P", 'p',
    "Q", 'q',
    "R", 'r',
    "S", 's',
    "T", 't',
    "U", 'u',
    "V", 'v',
    "W", 'w',
    "X", 'x',
    "Y", 'y',
    "Z", 'z',
    "Backspace", "Enter"
];

const wordPool = [
    'power', 'force', 'fires', 'tests', 'agent', 'cycle', 'phase',
    'pests', 'raids', 'enemy', 'peril', 'wound', 'thing', 'virus',
    'snake', 'blows', 'venom', 'fight', 'feuds', 'fever', 'chill',
    'quiet', 'gases', 'germs', 'fumes', 'death', 'crime', 'storm',
    'means', 'hands', 'pains', 'shock', 'winds', 'scene', 'anger',
    'games', 'brown', 'night', 'color', 'cloud', 'place', 'spots',
    'green', 'lines', 'water', 'field', 'bands', 'hours', 'blood',
    'woods', 'space', 'house', 'trees', 'rooms', 'shape', 'horse',
    'suits', 'earth', 'dress', 'alley', 'faces', 'walls', 'curls',
    'women', 'woman', 'smoke', 'holes', 'magic', 'cloth', 'males',
    'beard', 'shoes', 'sheep', 'paint', 'stone', 'boots', 'bread',
    'paper', 'shirt', 'music', 'youth', 'plant', 'weeds', 'doses',
    'drugs', 'herbs', 'juice', 'fangs', 'fruit', 'bites', 'fungi',
    'fluid', 'sting', 'seeds', 'stuff', 'roots', 'viper', 'foods',
    'honey', 'state', 'moods', 'style', 'guilt', 'party', 'pleas',
    'smile', 'start', 'child', 'souls', 'fears', 'cause', 'heads',
    'deeds', 'shame', 'words', 'front', 'stand', 'chief', 'sight',
    'laugh', 'wreck', 'habit', 'arise', 'awake', 'apple', 'board',
    'break', 'order', 'asail', 'abide', 'about', 'black', 'breed',
    'begin', 'issue', 'block', 'burst', 'bring', 'index', 'build',
    'bleed', 'along', 'idiom', 'angle', 'bigly', 'bound', 'after',
    'image', 'brace', 'bigot', 'upset', 'irony', 'asset', 'input',
    'infer', 'array', 'blind', 'urban', 'brief', 'apart', 'being',
    'apply', 'abuse', 'bleak', 'banal', 'doubt', 'other', 'incur',
    'idium', 'agile', 'aside', 'acute', 'boost', 'bliss', 'union',
    'align', 'avail', 'brand', 'aloof', 'axiom', 'amend', 'adage',
    'borne', 'blunt', 'angst', 'organ', 'abate', 'alert', 'above',
    'dogma', 'basis', 'blast', 'offer', 'ideal', 'adept', 'aware',
    'adapt', 'bitch', 'again', 'inure', 'inane', 'aegis', 'allow',
    'angel', 'beach', 'ardor', 'ocean', 'avoid', 'overt', 'idiot',
    'agree', 'ought', 'ahead', 'brood', 'asyla', 'under', 'world',
    'abyss', 'often', 'imbue', 'alone', 'alien', 'bully', 'heart',
    'argue', 'blade', 'alloy', 'belie', 'brake', 'alter', 'askew',
    'bloom', 'aster', 'adopt', 'imply', 'among', 'basic', 'aerie',
    'aisle', 'occur', 'assay', 'audit', 'brain', 'brave', 'awash',
    'avert', 'ombre', 'brime', 'ultra', 'bluff', 'azure', 'abbey',
    'awful', 'broad', 'utter', 'becon', 'beset', 'admit', 'aleve',
    'blaze', 'brass', 'abset', 'blank', 'opine', 'brush', 'appal',
    'award', 'boast', 'blend', 'abhor', 'annex', 'ambit', 'bumpy',
    'allay', 'blame', 'angry', 'inept', 'algae', 'donny', 'clown',
    'agape', 'usurp', 'beget', 'basin', 'berry', 'augur', 'inter',
    'alive', 'bland', 'aglow', 'alpha', 'inlay', 'brash', 'agora',
    'inert', 'opera', 'bible', 'bench', 'dodge', 'orbit', 'ahold',
    'binge', 'birth', 'alias', 'amber', 'brine', 'unity', 'arena',
    'until', 'ample', 'usage', 'imago', 'auger', 'berth', 'dough',
    'blase', 'amage', 'ariat', 'alarm', 'orris', 'onset', 'oasis',
    'altar', 'brisk', 'brook', 'omega', 'bosom', 'onion', 'argot',
    'amity', 'doozy', 'batch', 'usher', 'ariel', 'birch', 'abase',
    'amiss', 'upend', 'adore', 'attic', 'bunch', 'umber', 'outre',
    'atlas', 'arete', 'annul', 'agave', 'alibi', 'ounce', 'anime',
    'bulge', 'blink', 'below', 'olive', 'umami', 'impel', 'adult',
    'biome', 'broom', 'blitz', 'brink', 'oomph', 'allot', 'ulcer',
    'agony', 'audio', 'bless', 'brick', 'outdo', 'booty', 'oxide',
    'arson', 'acrid', 'intel', 'okapi', 'arrow', 'atone', 'bezel',
    'aroma', 'offal', 'abode', 'buddy', 'dozen', 'beast', 'blurb',
    'bacon', 'irate', 'avian', 'adorn', 'bored', 'ochre', 'booth',
    'undue', 'anima', 'bough', 'dodgy', 'umbra', 'based', 'bling',
    'atoll', 'aging', 'apnea', 'islam', 'bogus', 'bevel', 'ictus',
    'blush', 'brawl', 'bonus', 'aught', 'brute', 'osier', 'affix',
    'bower', 'bravo', 'annoy', 'baton', 'barge', 'armor', 'adieu',
    'idyll', 'actor', 'ovate', 'bones', 'agate', 'baron', 'braid',
    'belly', 'aspen', 'adams', 'alike', 'orate', 'uvula', 'bride',
    'usury', 'arbor', 'douse', 'adobe', 'apron', 'inner', 'aural',
    'aback', 'antic', 'budge', 'argus', 'assai', 'aioli', 'bribe',
    'otter', 'badge', 'anvil', 'amble', 'doyen', 'owner', 'usual',
    'antsy', 'aloft', 'amaze', 'odium', 'aorta', 'ovine', 'ihram',
    'buggy', 'anent', 'indie', 'avast', 'await', 'dowry', 'beans',
    'bugle', 'aloha', 'ilium', 'intra', 'amuse', 'bayou', 'ichor',
    'inlet', 'bison', 'blues', 'bolus', 'dicky', 'dolly', 'uncle',
    'alder', 'orion', 'beige', 'adder', 'amass', 'ovolo', 'blond',
    'afoul', 'amast', 'oriel', 'optic', 'blimp', 'apnic', 'areal',
    'bimbo', 'basil', 'apace', 'addle', 'bijou', 'arose', 'donut',
    'belay', 'bursa', 'abash', 'brunt', 'anise', 'broke', 'amour',
    'album', 'balmy', 'bloke', 'built', 'afoot', 'igloo', 'osage',
    'belle', 'dowdy', 'amish', 'baker', 'broth', 'attar', 'beech',
    'botch', 'books', 'annal', 'india', 'booze', 'broil', 'bandy',
    'ivory', 'ogive', 'beryl', 'breve', 'acorn', 'barre', 'ionic',
    'alamo', 'bawdy', 'bella', 'donna', 'unite', 'bossy', 'aaron',
    'aries', 'arras', 'irene', 'ascot', 'inuit', 'argon', 'asian',
    'babel', 'bogey', 'boner', 'brier', 'urari', 'batik', 'bowel',
    'amati', 'ollie', 'ingle', 'astir', 'abbot', 'dower', 'aloud',
    'bream', 'beaux', 'obese', 'ozone', 'bleek', 'alice', 'oribi',
    'ankle', 'donor', 'bunny', 'bloat', 'birds', 'infra', 'ileum',
    'allen', 'aspic', 'atria', 'amite', 'buxom', 'betty', 'burly',
    'bleat', 'opium', 'brawn', 'anode', 'apsis', 'arden', 'beret',
    'bight', 'inapt', 'bingo', 'ingot', 'basal', 'briar', 'ashen',
    'acini', 'axial', 'bagel', 'began', 'aline', 'indri', 'ukase',
    'bilge', 'blanc', 'doral', 'adhoc', 'abort', 'apian', 'anile',
    'oscar', 'odeon', 'bidet', 'dicey', 'obeli', 'angus', 'aptly',
    'inset', 'istle', 'biota', 'bleam', 'burro', 'braud', 'butte',
    'amino', 'bruit', 'ocher', 'avant', 'odour', 'blown', 'ortho',
    'boyle', 'aryan', 'bathe', 'aphid', 'amuck', 'baste', 'ousel',
    'blini', 'acela', 'badly', 'baize', 'ideas', 'beano', 'afore',
    'icing', 'abaft', 'akita', 'imari', 'burnt', 'ackee', 'balls',
    'upper', 'octet', 'doily', 'benin', 'doing', 'irish', 'blurt',
    'arhat', 'billy', 'ionia', 'ology', 'aglet', 'asana', 'baulk',
    'islet', 'blest', 'ament', 'doric', 'amain', 'balsa', 'betel',
    'orlop', 'booby', 'auric', 'dowel', 'ovule', 'bongo', 'annum',
    'odeum', 'brock', 'alife', 'bonny', 'outer', 'abaca', 'bells',
    'indra', 'brill', 'bohea', 'obeah', 'bucky', 'agita', 'umbel',
    'adios', 'alore', 'andes', 'anele', 'blate', 'addax', 'banks',
    'owing', 'afire', 'blear', 'imbed', 'indus', 'antre', 'abysm',
    'bases', 'besom', 'blare', 'bosun', 'astro', 'oread', 'biter',
    'bears', 'ostia', 'allah', 'aesop', 'agami', 'using', 'aspin',
    'bantu', 'unsew', 'dicot', 'ouchy', 'uther', 'ashes', 'dicta',
    'italy', 'boxer', 'aleph', 'awoke', 'bombe', 'udder', 'bangs',
    'aunty', 'belch', 'iliad', 'befit', 'bylaw', 'doggo', 'unify',
    'braze', 'idler', 'areca', 'abele', 'doula', 'dotty', 'iliac',
    'basso', 'butch', 'april', 'baggy', 'brive', 'amase', 'aitch',
    'oakum', 'dowty', 'agist', 'asses', 'isaac', 'amine', 'abeam',
    'anion', 'ovoid', 'ileus', 'bambi', 'banjo', 'aurum', 'blair',
    'dopey', 'ouija', 'astor', 'boron', 'braun', 'doyle', 'bowie',
    'bulky', 'idaho', 'acerb', 'bonds', 'dolce', 'icier', 'bulla',
    'bronx', 'bunce', 'burke', 'oding', 'orvis', 'artic', 'acids',
    'anglo', 'barry', 'octal', 'bated', 'added', 'bogie', 'dover',
    'amore', 'allie', 'biped', 'urine', 'doggy', 'begot', 'oligo',
    'bract', 'omaha', 'blake', 'amigo', 'bruce', 'ornis', 'acton',
    'arian', 'aggro', 'ascii', 'algid', 'bebop', 'oxeye', 'idion',
    'orang', 'apara', 'bared', 'briny', 'ormer', 'beads', 'downy',
    'brite', 'donne', 'armed', 'doris', 'amice', 'aruba', 'bhaji',
    'begat', 'banta', 'alate', 'agama', 'artsy', 'iraqi', 'aphis',
    'borer', 'aviso', 'irons', 'ident', 'items', 'bindi', 'bowed',
    'asean', 'barmy', 'downs', 'blite', 'bally', 'atall', 'batty',
    'burka', 'abend', 'belli', 'boson', 'aztec', 'icily', 'burma',
    'inbox', 'ogham', 'ouzel', 'brome', 'annie', 'dolor', 'aping',
    'owlet', 'ugric', 'utero', 'armet', 'aieee', 'incus', 'baded',
    'ameba', 'allee', 'dowse', 'oddly', 'osaka', 'bromo', 'ontic',
    'uteri', 'intex', 'avery', 'aesir', 'agasp', 'arear', 'brest',
    'bairn', 'bento', 'accra', 'arial', 'octad', 'amara', 'slash',
    'itchy', 'azeri', 'bocce', 'brava', 'doors', 'omani', 'aleck',
    'adobo', 'appel', 'baser', 'boney', 'asked', 'balti', 'iodin',
    'avers', 'assam', 'burns', 'botox', 'bobby', 'beady', 'bushy',
    'blume', 'brant', 'bahai', 'aggie', 'bilbo', 'avens', 'boned',
    'beefy', 'bruin', 'dorky', 'intro', 'doner', 'ovary', 'broid',
    'arced', 'basel', 'begor', 'borax', 'outof', 'bogan', 'bowls',
    'ameer', 'blive', 'antra', 'inkle', 'bonce', 'akela', 'blain',
    'argos', 'biddy', 'ulema', 'apish', 'boule', 'baked', 'amana',
    'osric', 'owned', 'aleut', 'aquae', 'atari', 'asher', 'ophir',
    'besot', 'uhlan', 'adele', 'brusk', 'adler', 'ation', 'begun',
    'alack', 'akbar', 'arris', 'inion', 'arana', 'adman', 'andre',
    'bleep', 'adour', 'atman', 'buyer', 'atbay', 'azoic', 'osteo',
    'abuja', 'anole', 'brume', 'bushi', 'dobby', 'byron', 'benji',
    'iorta', 'ohmic', 'bider', 'biker', 'bodhi', 'ashet', 'imide',
    'babka', 'areas', 'bando', 'beats', 'bumps', 'owens', 'auden',
    'bueno', 'uredo', 'bloop', 'brady', 'ibsen', 'orlon', 'bitty',
    'bourn', 'ulnar', 'boone', 'brail', 'older', 'aides', 'oiler',
    'isles', 'actin', 'ammon', 'athos', 'betid', 'donee', 'boise',
    'abuts', 'oldie', 'optus', 'uncut', 'acres', 'abuzz', 'admin',
    'oxlip', 'adlib', 'anjou', 'oaker', 'amort', 'boxes', 'utica',
    'baler', 'bazar', 'bucks', 'aloes', 'oxbow', 'anker', 'inurn',
    'unfit', 'addie', 'arles', 'brose', 'islay', 'apery', 'ibiza',
    'boggy', 'ixion', 'artel', 'beaut', 'bruno', 'akron', 'arsis',
    'ilial', 'aeiou', 'berka', 'boobs', 'argil', 'brent', 'iroko',
    'acari', 'benny', 'bogue', 'bunco', 'orpin', 'axion', 'olmec',
    'accel', 'amide', 'iceni', 'oboli', 'burse', 'irked', 'unlax',
    'boist', 'asper', 'alula', 'amply', 'bokeh', 'bwana', 'izard',
    'oflag', 'agone', 'brach', 'invar', 'botty', 'brack', 'burry',
    'dozer', 'algol', 'bicep', 'bosch', 'utile', 'agnes', 'atopy',
];

export { allowedKeys, wordPool, keyindex };